version: '2.4'

services:
  db:
    image: postgres:13.3-alpine
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - news_pgdata:/var/lib/postgresql/data/

  redis:
    image: redis:6-alpine
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - news_redis:/data

volumes:
  news_pgdata:
  news_redis: