version: '2.4'

#x-base: &base
#  restart: unless-stopped
#  networks:
#    - app-network

x-app: &app
#  <<: *base
  env_file:
    - ./.env
  build:
    context: .
    dockerfile: Dockerfile
    network: host

  depends_on:
    redis:
      condition: service_started
    db:
      condition: service_started

services:
#  web:
#    <<: *app
#    command: uvicorn adfox_int.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
#    ports:
#      - 80:8000
#
#  celery:
#    <<: *app
#    working_dir: /code/src
#    command: celery --app=news.celery_workers.celery worker --beat --loglevel=debug

  db:
    image: postgres:13.3-alpine
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - news_pgdata:/var/lib/postgresql/data/

  redis:
    image: redis:6-alpine
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - news_redis:/data

volumes:
  news_pgdata:
  news_redis: